apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Values.nfs.claim }}"
spec:
  storageClassName: "rook-nfs-{{ .Values.nfs.path }}"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "{{ .Values.nfs.size }}"
