repositories:
  - name: dgraph
    url: https://charts.dgraph.io

releases:
  {{- if eq (env "NFS_STRATEGY") "rook" }}
  - name: rook-nfs-operator
    ## NOTE: namespace must also be specified in
    ##  ./rook-nfs-operator-kustomize/overlays/default/kustomization.yaml
    namespace: rook-nfs-system
    ## temporary helm chart rendered by helmify
    chart: ./rook-nfs-operator
    hooks:
      - events:
          - prepare
          - cleanup
        command: ./helmify.sh
        args:
          - "{{`{{if eq .Event.Name \"prepare\"}}build{{else}}clean{{end}}`}}"
          - "{{`{{.Release.Chart}}`}}"
          - default

  - name: rook-nfs-server
    ## NOTE: namespace must also be specified in
    ##  ./rook-nfs-server-kustomize/overlays/default/kustomization.yaml
    namespace: rook-nfs-system
    ## temporary helm chart rendered by helmify
    chart: ./rook-nfs-server
    values:
      - nfs:
          size: {{ env "NFS_SIZE" | default "32Gi" }}
          path: {{ env "NFS_PATH" | default "share1" }}
    hooks:
      - events:
          - prepare
          - cleanup
        command: ./helmify.sh
        args:
          - "{{`{{if eq .Event.Name \"prepare\"}}build{{else}}clean{{end}}`}}"
          - "{{`{{.Release.Chart}}`}}"
          - default
    needs:
      - rook-nfs-system/rook-nfs-operator
    disableValidation: true

  - name: rook-nfs-storageclass
    ## NOTE: namespace must also be specified in
    ##  ./rook-nfs-storageclass-kustomize/overlays/default/kustomization.yaml
    namespace: rook-nfs-system
    ## temporary helm chart rendered by helmify
    chart: ./rook-nfs-storageclass
    values:
      - nfs:
          server: {{ env "NFS_SERVER" | default "rook-nfs" }}
          path: {{ env "NFS_PATH" | default "share1" }}
          namespace: rook-nfs-system
          size: {{ env "NFS_SIZE" | default "32Gi" }}
          claim: {{ env "NFS_CLAIM" | default "rook-nfs-pv-claim" }}
    hooks:
      - events:
          - prepare
          - cleanup
        command: ./helmify.sh
        args:
          - "{{`{{if eq .Event.Name \"prepare\"}}build{{else}}clean{{end}}`}}"
          - "{{`{{.Release.Chart}}`}}"
          - default
  {{- end }}

  - name: my-release
    namespace: default
    chart: dgraph/dgraph
    values:
      - ./dgraph_{{ env "NFS_TYPE" | default "static" }}_nfs.yaml
      - backups:
          ## NFS using statically assigned values with NFS_SERVER and NFS_PATH env vars
          {{- if eq (env "NFS_TYPE") "static" }}
          nfs:
            server: {{ env "NFS_SERVER" }}
            path: {{ env "NFS_PATH" }}
            storage: {{ env "NFS_SIZE" | default "32Gi" }}
          {{- else if eq (env "NFS_TYPE") "dynamic" }}
          ## NFS dynamically allocated using NFS volume claim
          volume:
            claim: {{ env "NFS_CLAIM" }}
          {{- end }}
